const Products = [
    {
        ProductId: 1,
        ProductName: 'Bánh mì 2 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 2,
        ProductName: 'Bánh mì 3 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 3,
        ProductName: 'Bánh mì 4 trứng dài',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 4,
        ProductName: 'Bánh mì 5 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1007,
    },
    {
        ProductId: 5,
        ProductName: 'Bánh mì 6 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 6,
        ProductName: 'Bánh mì 7 trứng dài thòn lòn test khoảng trắng dư chấm chấm',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 7,
        ProductName: 'Bánh mì 8 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 8,
        ProductName: 'Bánh mì 9 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 9,
        ProductName: 'Bánh mì 10 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 10,
        ProductName: 'Bánh mì 11 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 11,
        ProductName: 'Bánh mì 12 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
    {
        ProductId: 12,
        ProductName: 'Bánh mì 13 trứng',
        Type: 'Tươi sống',
        Image: '../../images/product1.png',
        Status: 1005,
    },
];

export default Products;